[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "mlx-graphs"
version = "0.0.1"
description = "Graph Neural Network library made for Apple Silicons"
authors = ["mlx-graphs contributors"]
readme = "README.md"
packages = [
  { include = "mlx-graphs" }
]
