name: build-sphinx-docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
           python-version: 3.11
      - name: Install Python dependencies
        run: python -m pip install .[docs]
      - name: Install Pandoc
        uses: pandoc/actions/setup@v1.0.0
        with:
          version: 2.19
      - name: Build sphinx
        run: |
          cd docs/
          make html
      - name: Deploy to external repos
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
