# This workflow runs:
# - the linting and formatting specified in the pre-commit hooks
# - tests for the package

name: PR

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:

    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -v '.[test]'
        pip install pre-commit
        pre-commit install
        which python
        pip list
    - name: Run lint
      run: |
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pytest tests/batch/test_batch.py -rx -v -l
