name: build-sphinx-docs

on:
  push:
    branches: ["gh_pages"]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: 3.12
      - name: Install dependencies
        run: python -m pip install .[docs]
      - name: Build sphinx
        run: |
          cd docs/
          make html
          # sphinx-build -b html source build
      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/build/html
