# This is a basic workflow to help you get started with Actions

name: build-sphinx-docs

on:
  push:
    branches: [ "gh_pages" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
           python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps ".[docs]"
          pip install sphinx==7.2.6 sphinx-book-theme==1.1.0 sphinx-autodoc-typehints==1.25.2
      - name: Build HTML
        run: |
          cd docs/
          make clean
          make html
      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/build/html
