name: test

on: [push]

jobs:
  testing:

    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install python@3.11
          python3.11 -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -e .
          pip isntall -e '.[test]'
      - name: Run tests
        run: |
          source env/bin/activate
          pytest
